/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.components;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import state.State;

/**
 *
 * @author siux
 */
public class PanelState extends javax.swing.JPanel{

    /**
     * Creates new form PanelState
     */
    public PanelState(State state) {
        initComponents();
        this.state = state;
        setStateName();
        //setBackground(Color.GREEN);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblStateName = new javax.swing.JLabel();

        lblStateName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        lblStateName.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStateName, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblStateName)
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void setStateName(){
        lblStateName.setText(state.toString());
    }

    public JLabel getLblStateName() {
        return lblStateName;
    }
    
    
    
    private State state;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblStateName;
    // End of variables declaration//GEN-END:variables

    
}
